### PR TITLE
Migrated from Gradle to Maven

### PR DESCRIPTION
**Pull request by chutchinson**
Please note if you agree or disagree with this change. Three team members are already comfortable using Maven. Maven tends to be faster, reliable, and has strong conventions. The major downside to Maven is verbosity. The major gain of this transition is to solve several problems with Gradle compatibility, the wrapper, and to prefer configuration over scripting (e.g. Groovy).

### CODE REVIEW

**Comment by goblinJoel** [comment]
Looking through a Maven NetBeans tutorial now for anything I might object to. However, the built-in NB support and increased speed you mention are compelling for me, plus this isn't a huge messy merge. The only thing I've noticed so far is that the commit removes the json dependency. It'd be nice if that stayed there, but it looks like it'll be easy to re-add.

**Comment by goblinJoel** [comment]
Aside from the missing dependency (which it looks like I could re-add by hand or via NB), I have no objections. If it makes it compile/run a little faster, still lets us auto-download dependencies, and has fewer weird behaviors in NB (since it's a standard plugin, I expect this), I'm for it.

**Comment by goblinJoel** [comment]
Today I Leanred that "Close and comment" means "close the request", not "close the comment window".

**Comment by chutchinson** [comment]
i added the missing dependency and cleaned up the maven subprojects.

**Pull request merged**
