### PR TITLE
Migrated to Gradle build system

### PR DESCRIPTION
**Pull request by chutchinson**
Migrated the project from a non-specific build system to Gradle. Please research and evaluate Gradle before accepting or revoking this pull request. The benefits are immense for relatively little cost. The use of a build system is paramount for large projects.

Basic instructions are available:

https://github.com/rpgtoolkit/editor/wiki/Build

### CODE REVIEW

**Comment by chutchinson** [comment]
Consider adding Eclipse / IDEA specific project files (especially those generated by Gradle) to the gitignore list.

**Comment by chutchinson** [comment]
The demo / testing project was also removed and should be re-added in a separate repository. They are not specific or necessary for the build. It is also acceptable to introduce the demo files as test dependencies for future unit testing - ensuring they conform to Gradle testing semantics and conventions.

**Comment by goblinJoel** [comment]
The test project is pretty necessary in order to actual do any work on the editor. However, I understand the rationale for splitting it into another repo. What's required to do that while keeping Gradle happy? Is it as simple as making a new repo and copying the test toolkit project into it before pulling the Gradle update? Or were you suggesting we integrate the test project into Gradle somehow?

I'm still going through the Gradle user guide and reading about the community-made NetBeans plugin, so I'm a little fuzzy on all this.

Caveat: I'm reading people as recently as 3/30/15 saying not to use Gradle 2.3 with NetBeans, as apparently there is a bug with Gradle that breaks certain features with that IDE. It's unclear whether that's resolved, so I'm hesitant to jump on board yet.

**Comment by chutchinson** [comment]
The test project is not necessary to work on the editor, it's necessary to test the functionality. It's acceptable to include example files for the purpose of unit testing; however, any files added should be included in the file structure according to the build system conventions. (e.g. http://gradle.org/docs/current/userguide/java_plugin.html)

The caveat you mentioned isn't an issue because we can add a version predicate to the Gradle build configuration to use version 2.2. Even without changing that I can confirm that the project currently loads, builds, runs, and otherwise works correctly within NetBeans.

Your concerns are reasonable. I suggest simply copying the "test project" files to a fresh repository and referencing that repository in the documentation. In the future, if and when unit testing is integrated into the project, specific test files can be added into the project structure (e.g. src/test/resources).

**Comment by goblinJoel** [comment]
Then I have no further objections, your honor.

I'll let swordmaster merge if he approves, as he's more or less in charge of this from my perspective.

I'll plan on making a new repo for a test project and put the current one (as of the enemy branch) in that so when this gets merged in, we'll have the replacement ready.

**Comment by chutchinson** [comment]
I created this documentation to assist:

https://github.com/rpgtoolkit/editor/wiki/Contributing

**Comment by goblinJoel** [comment]
Looks like I don't have permissions to make a new repo in this project, which is fine, but it means someone else will need to make the test project repo if we want a shared one. Otherwise I guess I could just make my own, but it seems like it might be useful to have a test project we can all use and reference.

**Comment by chutchinson** [comment]
https://github.com/rpgtoolkit/demo

**Pull request merged**
